### ISSUE TITLE
Can this portmapper be used as a library of a different program?

### ISSUE THREAD

**Issue by brunoais** [kaklakariada/portmapper#51]
If so, any documentation on that?

**Comment by kaklakariada** [comment]
Yes, you could use it as a library, but it is not published to a Maven repo.
You can see how to connect to a router at https://github.com/kaklakariada/portmapper/blob/master/src/main/java/org/chris/portmapper/PortMapperApp.java#L199

**Comment by brunoais** [comment]
Great! Thank you. It's OK it is not on maven, though.

**Comment by kaklakariada** [comment]
I know how to deploy to Maven, it's just I didn't do it for PortMapper yet. Maybe I have time this weekend...

**Comment by brunoais** [comment]
Awesome. Thank you.

**Comment by kaklakariada** [comment]
I just published to jcenter. It may take some time until it is available at https://jcenter.bintray.com/com/github/kaklakariada/

In the meantime you can use this repo url: https://dl.bintray.com/kaklakariada/maven

Maven coordinates: `'com.github.kaklakariada:portmapper:2.2.0'`

You might want to use the jar `with-dependencies` because it contains libraries not available in a public maven repo.

Please let me know if it works for you!

**Comment by brunoais** [comment]
That is above and beyond what I wanted to work with. Thank you very much.
Thank you for the instructions too.

**Comment by kaklakariada** [comment]
You are welcome :)
I am happy that you find it useful!
The jars are now available on jcenter: https://jcenter.bintray.com/com/github/kaklakariada/portmapper/2.2.0/
