### ISSUE TITLE
portmapper fails with my router

### ISSUE THREAD

**Issue by ravn** [kaklakariada/portmapper#53]
Checked out the latest sources (7a4d7fc28fed0576260fd6ef339128e6fce2fac4).  After pressing Connect the log shows:

```
DEBUG Getting port mapping with entry number 0...
ERROR Invocation (ActionInvocation) (Action, Arguments: 9) GetGenericPortMappingEntry failed with operation '500 Internal Server Error', body '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
 <s:Body>
  <s:Fault>
   <faultcode>s:Client</faultcode>
   <faultstring>UPnPError</faultstring>
   <detail>
    <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
     <errorCode>713</errorCode>
     <errorDescription>SpecifiedArrayIndexInvalid</errorDescription>
    </UPnPError>
   </detail>
  </s:Fault>
 </s:Body>
</s:Envelope>
'
INFO  Got error response when fetching port mapping for entry number 0: '(IncomingActionResponseMessage) 500 Internal Server Error'. Stop getting more entries.
```

**Comment by kaklakariada** [comment]
Hi @ravn,
Thanks for using PortMapper! This error message is 'expected'. UPnP does not allow getting the number of port mappings. That's why PortMapper continues fetching the mappings until it receives an error like the one you saw (`SpecifiedArrayIndexInvalid`). PortMapper tries to retrieve entry 0 and gets this error. This means there is currently no mapping configured in your router.

Does this answer your question?

**Comment by kaklakariada** [comment]
Closing as stale.
