### ISSUE TITLE
Promblems with network not allowing PortMapper

### ISSUE THREAD

**Issue by Bluelight82** [kaklakariada/portmapper#90]
I used PortMapper 2.1.1 fine a few weeks ago, and nothing has changed network wise that I know of, but now I suddenly get this error: 
`INFO  Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
INFO  Searching for routers...
INFO  >>> Starting UPnP service...
INFO  Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
INFO  Creating Router: org.fourthline.cling.transport.RouterImpl
INFO  Creating wildcard socket (for receiving multicast datagrams) on port: 1900
INFO  Joining multicast group: /239.255.255.250:1900 on network interface: Intel(R) Ethernet Connection (7) I219-V
INFO  Created server (for receiving TCP streams) on: /**removedIP**
INFO  Creating bound socket (for datagram input/output) on: /**removedIP**
ERROR Unable to initialize network router: org.fourthline.cling.transport.spi.InitializationException: Failed to set modified URLStreamHandlerFactory in this environment. Can't use bundled default client based on HTTPURLConnection, see manual.
ERROR Cause: org.fourthline.cling.transport.spi.InitializationException: Failed to set modified URLStreamHandlerFactory in this environment. Can't use bundled default client based on HTTPURLConnection, see manual.
INFO  <<< UPnP service started successfully
WARN  Could not connect to router: Did not find a router
org.chris.portmapper.router.RouterException: Did not find a router
	at org.chris.portmapper.PortMapperApp.connectRouter(PortMapperApp.java:220)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:456)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:444)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
WARN  Could not connect to router: Did not find a router`

Did the ISP change something in the router? I used the first UPnP librarybefore, that gives and error now. I can select the third library option but it gets stuck when Editing and creating presets, and after a long time it tells me that it was not possible to find localhost IP or something. Could it be a Firewall issue?

**Comment by Bluelight82** [comment]
It is not a firewall issue! Just tested every possible combinations of disabling firewall and anti-virus.

**Comment by kaklakariada** [comment]
Did you get this message before: `Failed to set modified URLStreamHandlerFactory in this environment. Can't use bundled default client based on HTTPURLConnection, see manual.`?

This could be caused by the Cling library in [StreamClientImpl](https://github.com/4thline/cling/blob/0ca10d5e73bdc8062eeffad57d67dd8ee260379c/core/src/main/java/org/fourthline/cling/transport/impl/StreamClientImpl.java#L115).

Did you change anything in your environment, e.g. install a new Java version?

You could try two things:

* Deactivate the relevant Cling code by starting PortMapper with `java -DhackStreamHandlerProperty=done -jar portmapper.jar`. But this might cause other issues.
* Use another UPnP library included in PortMapper.

**Comment by kaklakariada** [comment]
Closing as stale.
